
# Experiment_1
# ------------
exp_1: &1
  # Description
  description: >
    This is an description of this experiment.
  # Hyper parameters
  hyperparams:
    epochs: 35
    random_state: 4
    batch_size: 25
    cell_num: 300
    layer_num: 1
    dropout_keep_prob: 0.5
    epsilon: 0.01
    momentum: 0.9
    learning_rate: 0.01
    lambda: 0.001 # l2
    optimizer: adagrad