# Basic cofnigs


symbol_dict:
# ----------
  path: data/processed/ATAE-LSTM/glove_symdict
  start_idx: 2 # 0 for padding, 1 for <UNK>

embedding_table:
# --------------
  path: data/processed/ATAE-LSTM/glove_lookup

lexicon_table:
# ------------
  path: data/processed/lexicon/lexicon_table
  usecol: -1

model:
# ----
  savepath: models/at-lstm/

exp_configs:
# ----------
  path: configs/atlstm_exp_configs
