# Basic cofnigs


symbol_dict:
# ----------
  path: data/processed/SemEval14/glove_symdict
  start_idx: 2 # 0 for padding, 1 for <UNK>

embedding_table:
# --------------
  path: data/processed/SemEval14/glove_lookup

lexicon_table:
# ------------
  path: data/processed/effective_lexicon/effective_lexicon
  usecol: 3
  lx_size: 1200
  append_neg: True

model:
# ----
  savepath: models/atlx/SemEval14/

exp_configs:
# ----------
  path: configs/atlx_exp_configs
