# Basic cofnigs


symbol_dict:
# ----------
  path: data/processed/SemEval14/glove_symdict
  start_idx: 2 # 0 for padding, 1 for <UNK>

embedding_table:
# --------------
  path: data/processed/SemEval14/glove_lookup

lexicon_table:
# ------------
  # path: data/processed/lexicon_v2/lexicon_table_v2
  path: data/processed/dalx/yelp_lexicon_table_dalx_14_thres0.7_C10
  usecol: 3
  lx_size: -1
  append_neg: False
  asp_lx: False

model:
# ----
  savepath: models/atlx/SemEval14/

exp_configs:
# ----------
  path: configs/atlx_exp_configs
