# Basic cofnigs


symbol_dict:
# ----------
  path: data/processed/SemEval15_laptop/glove_symdict
  start_idx: 2 # 0 for padding, 1 for <UNK>

embedding_table:
# --------------
  path: data/processed/SemEval15_laptop/glove_lookup

lexicon_table:
# ------------
  path: data/processed/dalx/lexicon_table_dalx_asp_12_thres0.7_C10_add
  usecol: 3
  lx_size: -1
  append_neg: False
  asp_lx: True

model:
# ----
  savepath: models/atlx/SemEval15_laptop/

exp_configs:
# ----------
  path: configs/atlx_exp_configs
