symbol_dict:
# ----------
  path:
    data/processed/ATAE-LSTM/glove_symdict.yml
  start_idx:
    2 # 0 for padding, 1 for <UNK>

embedding_table:
# --------------
  path:
    data/processed/ATAE-LSTM/glove_lookup.parquet

model:
# ----
  path: models/
  name: AT-LSTM

hyperparams:
# ----------
  epochs: 35
  random_state:
  batch_size: 25
  cell_num: 300
  layer_num: 1
  dropout_keep_prob: 0.5
  epsilon: 0.01
  momentum: 0.9
  learning_rate: 0.01
  lambda: 0.001