# Logging config file for tgmle.Logger()

version: 1

disable_existing_loggers: False

formatters:
    simple:
      format: "%(asctime)s - %(message)s"
    normal:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    file_handler:
        class: logging.FileHandler
        level: INFO
        formatter: normal
        filename: logs/info.log
        encoding: utf8
    file_handler2:
        class: logging.FileHandler
        level: 99
        formatter: simple
        filename: logs/tuning.log
        encoding: utf8
    rotating_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: normal
      filename: logs/debug.log
      maxBytes: 10485760 #10MB
      backupCount: 1
      encoding: utf8

root:
  level: DEBUG
  handlers: [console, file_handler, file_handler2, rotating_handler]
